---
# tasks file for docker

- name: Install base security prerequisites for Docker CE
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Get upstream APT GPG key
  apt_key:
    # TODO fix get key
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    keyserver: '{{ ansible_local.core.keyserver
                if (ansible_local|d() and ansible_local.core|d() and
                   ansible_local.core.keyserver)
                else "hkp://pool.sks-keyservers.net" }}'
    state: 'present'

- name: Configure upstream APT repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  notify:
    - start docker