# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "ubuntu/xenial64"
NODES = 3

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

	# master VM
	config.vm.define "master", primary: true do |master|
		master.vm.box = BOX
		master.vm.hostname = "master"
		master.vm.network "private_network", ip: "192.168.33.10"
		master.vm.network :forwarded_port, guest: 22, host: 10022, id: "ssh"

		# Virtualbox VM provider  
		master.vm.provider "virtualbox" do |vb|
			# Customize the amount of memory on the VM:
			vb.memory = 512
			vb.cpus = 1
			vb.name = "master"
		end
		
		config.vm.provision "ansible_local" do |ansible|
			# Avoid installing on tests
			ansible.install = "false"
			# ansible.install = "true"
			ansible.version = "latest"
			ansible.playbook = "master.yml"
		end

	end
      
	(1..NODES).each do |i|
		# node VM
		config.vm.define "node#{i}" do |node|
			node.vm.box = "ubuntu/xenial64"
			node.vm.hostname = "node#{i}"
			node.vm.network "private_network", ip: "192.168.33.1#{i}"
			node.vm.network :forwarded_port, guest: 22, host: "10#{i}22", id: "ssh"

			# Virtualbox VM provider  
			node.vm.provider "virtualbox" do |vb|
				# Customize the amount of memory on the VM:
				vb.memory = 512
				vb.cpus = 1
				vb.name = "node#{i}"
			end
					
			node.vm.provision "ansible_local" do |ansible|
				# Avoid installing on tests
				ansible.install = "false"
				# ansible.install = "true"
				ansible.version = "latest"
				ansible.playbook = "node.yml"
			end
		end
	end

	# config.vm.synced_folder "../data", "/vagrant_data"

	# Enable provisioning with a shell script. Additional provisioners such as
	# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
	# documentation for more information about their specific syntax and use.
	# config.vm.provision "shell", inline: <<-SHELL
	#   apt-get update
	#   apt-get install -y apache2
	# SHELL
end
